---
title: JSIS Task Force analysis
author:
- "[Phil Neff](https://github.com/philneff)"
date: 10 January, 2021
output:
    html_document:
        html_preview: true
        toc: true
        toc_depth: 3
        toc_float: true
        code_folding: hide
---

```{r import, message = FALSE, warning = FALSE}

pacman::p_load(tidyverse, lubridate, here, skimr, yaml, ggplot2, ggalt, gplots,
               sf, rnaturalearth, rnaturalearthdata, maps, tools, RColorBrewer
               )

inputfile <- here::here("write/input/uw-chr-i213-public.csv.gz")

i213 <- read_delim(
    inputfile, delim = "|", 
    col_types = cols(
        # .default                     = col_character(),
        source                       = col_character(),
        sex                          = col_character(),
        cmplxn                       = col_character(),
        country_of_citizenship       = col_factor(),
        year                         = col_double(),
        month                        = col_double(),
        day                          = col_double(),
        hour                         = col_double(),
        minute                       = col_double(),
        fy                           = col_double(),
        age                          = col_double(),
        accompanied_juvenile_flag    = col_double(),
        unaccompanied_juvenile_flag  = col_double(),
        custody_redetermination_flag = col_double()
))

i213 <- i213 %>%
  mutate(across(where(is.character), ~ na_if(.,"")))

# Only looking at records obtained via ICE, which include Border Patrol/CBP apprehensions
i213 <- i213 %>%
    filter(source != "cbp")

```


## Data overview

```{r skim, message = FALSE, warning = FALSE}

i213 %>% skimr::skim()

```

## Count of records by state

```{r state}

state <- i213 %>%
   count(state, sort = TRUE)

state

```

## Count of OR/WA records by year

```{r year, message = FALSE, warning = FALSE}


ann <- i213 %>%
    filter(state %in% c("OR", "WA")) %>% 
    count(state, year) %>%
    pivot_wider(names_from = state, values_from = n,
                values_fill = list(n = 0)) %>%
    arrange(year)

ann

```

## Count of records by apprehension day of week

```{r weekday, message = FALSE, warning = FALSE}

day_of_week <- function(year, month, day) {
    dt <- as.Date(paste(year, month, day, sep = "-"))
    wd <- weekdays(dt, abbreviate = TRUE)
    wd <- as.factor(wd)
    fct_relevel(wd, c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))
}

wkdy <- i213 %>%
    filter(state %in% c("OR", "WA")) %>% 
    filter(!is.na(day)) %>%
    mutate(weekday = day_of_week(year, month, day)) %>%
    count(state, weekday) %>%
    pivot_wider(names_from = state, values_from = n)

wkdy

```

## Count of records by month

(Small number of pre-2018 records filtered out below)

```{r year_month}

# This could be better: e.g. overlapping lines per year

mth <- i213 %>%
    filter(state %in% c("OR", "WA")) %>% 
    filter(year > 2018) %>% 
    filter(!is.na(month)) %>%
    count(state, year, month) %>% 
    mutate(year_mon = zoo::as.yearmon(paste(year, month, sep='-')))

p1 <- mth %>% 
  ggplot(aes(x=year_mon, y=n)) +
  geom_col(aes(x=year_mon, y=n)) +
  facet_wrap(~state)

p1

```

## Count of records by hour of day

```{r time_of_day}

time <- i213 %>%
    filter(state %in% c("OR", "WA")) %>% 
    filter(!is.na(hour)) %>%
    count(state, hour)

p1 <- time %>% 
  ggplot(aes(x=hour, y=n)) +
  geom_col(aes(x=hour, y=n)) +
  facet_wrap(~state)

p1

```

## Demographics

"Complexion" values are decoded following ["The Border's Long Shadow"](https://www.aclumich.org/en/publications/borders-long-shadow) (ACLU of Michigan, 2021).

```{r demographics, message = FALSE, warning = FALSE}

i213 %>% 
    filter(state %in% c("OR", "WA")) %>% 
  group_by(state, country_of_citizenship) %>% 
  count(country_of_citizenship, sort=TRUE) %>% 
    pivot_wider(names_from = state, values_from = n)
  
i213 %>%
    filter(state %in% c("OR", "WA")) %>% 
    filter(!is.na(age), !is.na(sex)) %>%
    mutate(age_group = cut(age,
                           breaks = c(0, 18, 25, 40, 60, Inf),
                           right = FALSE)) %>%
    group_by(state, sex, age_group) %>% 
    count(sex, age_group) %>%
    pivot_wider(names_from = sex, values_from = n)

good_values <- c("ALBINO",
                 "BLACK",
                 "DARK BROWN",
                 "DARK",
                 "FAIR",
                 "LIGHT BROWN",
                 "LIGHT",
                 "MEDIUM BROWN",
                 "MEDIUM",
                 "OLIVE",
                 "RUDDY",
                 "SALLOW",
                 "YELLOW")

i213 <- i213 %>%
          mutate(cmplxn = case_when(
            cmplxn %in% good_values ~ cmplxn,
            is.na(cmplxn) ~ NA_character_,
            TRUE ~ "OTHER"))

i213 %>% 
  filter(state %in% c("OR", "WA")) %>% 
  group_by(state, cmplxn) %>% 
  count(cmplxn, sort = TRUE)

```
